# language: python

# python:
#   - "2.7"
#   - "3.4"
#   - "3.5"
#   - "3.6"    
  
# script: python app.py
language: bash
sudo : required

services:
- docker 

script:
- echo "hello bash travis file"

